### ISSUE TITLE
fastavro-gen not able to parse logical type decimal

### ISSUE THREAD

**Issue by tradercentric** [gudjonragnar/fastavro-gen#13]
Hi,

I am having issue generate python classes with this schema input

```json
{
  "namespace": "com.edmw.issuerlist",
  "type": "record",
  "name": "IssuerListMember",
  "fields": [
    {"name": "IssuerListCode", "type": "string"},
    {"name": "IssuerUniqueIdentifiers", "type": {"type" : "array", "items": "long"}},
    {"name": "LastUpdateTimestamp", "type": {
      "type": "long",
      "logicalType":  "timestamp-millis"
    }},
    {
      "default": null,
      "name": "IssuerMarketCap",
      "type": [
               "null",
               {
                 "logicalType": "decimal",
                 "precision": 38,
                 "scale": 8,
                 "type": "bytes"
               }
              ]
     }
  ]
}
```

Here is the stack trace:
```bash
(venv) C:\Users\----\JetBrain\workspace\python\kafka_learning>fastavro_gen IssuerList.avsc
Parsing schema/s for IssuerList.avsc
Generate dataclasss...
Traceback (most recent call last):
  File "C:\Users\----\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\----\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\----\JetBrain\workspace\python\kafka_learning\venv\Scripts\fastavro_gen.exe\__main__.py", line 7, in <module>
  File "c:\users\----\jetbrain\workspace\python\kafka_learning\venv\lib\site-packages\fastavro_gen\__main__.py", line 56, in main
    read_schemas_and_generate_classes(
  File "c:\users\----\jetbrain\workspace\python\kafka_learning\venv\lib\site-packages\fastavro_gen\type_gen.py", line 280, in read_schemas_and_generate_classes
    generate_classes(
  File "c:\users\----\jetbrain\workspace\python\kafka_learning\venv\lib\site-packages\fastavro_gen\type_gen.py", line 243, in generate_classes
    write_schema(
  File "c:\users\----\jetbrain\workspace\python\kafka_learning\venv\lib\site-packages\fastavro_gen\type_gen.py", line 214, in write_schema
    write_record(
  File "c:\users\----\jetbrain\workspace\python\kafka_learning\venv\lib\site-packages\fastavro_gen\type_gen.py", line 164, in write_record
    t = _parse_type(field["type"], collector, namespace_prefix=namespace_prefix)
  File "c:\users\----\jetbrain\workspace\python\kafka_learning\venv\lib\site-packages\fastavro_gen\type_gen.py", line 71, in _parse_type
    return f"Optional[{_parse_type(_other[0], collector, namespace_prefix=namespace_prefix)}]"
  File "c:\users\----\jetbrain\workspace\python\kafka_learning\venv\lib\site-packages\fastavro_gen\type_gen.py", line 78, in _parse_type
    return _parse_dict_type(_type, collector, namespace_prefix=namespace_prefix)
  File "c:\users\----\jetbrain\workspace\python\kafka_learning\venv\lib\site-packages\fastavro_gen\type_gen.py", line 109, in _parse_dict_type
    raise Exception(f"Failed parsing type {_type}")
Exception: Failed parsing type {'logicalType': 'decimal', 'precision': 38, 'scale': 8, 'type': 'bytes'}
```

**Comment by gudjonragnar** [comment]
Sorry for the late response, I haven't added any support for `bytes` type. You are welcome to submit a PR to fix that.

**Comment by ilijaljubicic** [comment]
This seems to fix it:

in fastavro_gen/type_gen.py:

```python
from decimal import Decimal

...


def _parse_dict_type(
    _type: dict,
    collector: Collector,
    *,
    namespace_prefix: str = "",
) -> str:
    if _type.get("type") == "bytes" and _type.get("logicalType") == "decimal":
        return "Decimal"

    if _type["type"] == "enum":
        return _parse_type(_type["name"], collector, namespace_prefix=namespace_prefix)
    elif _type["type"] == "map":
        collector.typing.add("Dict")
        return f"Dict[str, {_parse_type(_type['values'], collector, namespace_prefix=namespace_prefix)}]"
    elif _type["type"] == "array":
        collector.typing.add("List")
        return f"List[{_parse_type(_type['items'], collector, namespace_prefix=namespace_prefix)}]"
    elif _type["type"] == "record":
        return _parse_type(_type["name"], collector, namespace_prefix=namespace_prefix)
    elif _type["type"] in PRIMITIVE_TO_TYPE:
        return PRIMITIVE_TO_TYPE[_type["type"]]
    else:
        raise Exception(f"Failed parsing type {_type}")

```

in fastavro_gen/from_dict.py:
```python
def _handle_type(_type, val, cls):
    """Helper method to handle different types"""
    if val is None:
        return val

    if not val:
        return val
    if _type in PRIMITIVES:
        return val

    # Patch: Handle Decimal
    if _type.__name__ == "Decimal" or str(_type) == "<class 'decimal.Decimal'>":
        from decimal import Decimal
        return Decimal(val)
        
    try:
        if is_dataclass(_type):
            return fromdict(_type, val)
        if _type.__origin__ == Literal:
            return val
        if _type._name == "List":
            return [_handle_type(_type.__args__[0], v, cls) for v in val]
        if _type._name == "Optional":
            return _handle_type(_type.__args__[0], val, cls)
        if _type._name == "Dict" and "ForwardRef" in str(_type.__args__):
            class_dict = {
                k: _handle_type(cls.__annotations__[k], v, cls) for k, v in val.items()
            }
            return cls(**class_dict)

        if _type._name == "Dict":
            return {k: _handle_type(_type.__args__[1], v, cls) for k, v in val.items()}

        if _type.__origin__ == Union:
            for t in _type.__args__:
                try:
                    return _handle_type(t, val, cls)
                except:
                    pass

    except:
        raise Exception("Failed parsing value {} with type {}".format(val, _type))
```

**Comment by ilijaljubicic** [comment]
Here is the PR: https://github.com/gudjonragnar/fastavro-gen/pull/16
